version: '2'
services:
  elasticsearch:
    image: 016526250478.dkr.ecr.us-west-1.amazonaws.com/elk-stack-elasticsearch/elk-stack 
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
  logstash:
    image: 016526250478.dkr.ecr.us-west-1.amazonaws.com/elk-stack-logstash/oss
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    image: 016526250478.dkr.ecr.us-west-1.amazonaws.com/elk-stack-kibana/oss
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge

